"""add mfa

Revision ID: 01ed7ccf231b
Revises: a8771c1010cb
Create Date: 2025-12-15 22:36:01.512981

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01ed7ccf231b"
down_revision: str | Sequence[str] | None = "a8771c1010cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the column as nullable first
    op.add_column("users", sa.Column("mfa_enabled", sa.Boolean(), nullable=True))
    # Set default to False for existing rows
    op.execute("UPDATE users SET mfa_enabled = false WHERE mfa_enabled IS NULL")
    # Alter to NOT NULL
    op.alter_column("users", "mfa_enabled", nullable=False)
    op.add_column("users", sa.Column("mfa_secret", sa.String(128), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "mfa_enabled")
    op.drop_column("users", "mfa_secret")
    # ### end Alembic commands ###
