"""add email verification fields

Revision ID: 29cdc4e8d424
Revises: 01ed7ccf231b
Create Date: 2025-12-16 13:33:51.162929

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29cdc4e8d424"
down_revision: str | Sequence[str] | None = "01ed7ccf231b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("verification_token", sa.String(length=128), nullable=True))
    op.add_column("users", sa.Column("verification_token_expires_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_username_key"), "users", type_="unique")
    op.create_index("uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True)
    op.create_index("uq_users_username_lower", "users", [sa.literal_column("lower(username)")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_users_username_lower", table_name="users")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.create_unique_constraint(op.f("users_username_key"), "users", ["username"], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False)
    op.drop_column("users", "email_verified_at")
    op.drop_column("users", "verification_token_expires_at")
    op.drop_column("users", "verification_token")
    # ### end Alembic commands ###
