"""added team flag

Revision ID: 49189b8c0233
Revises: e22ba8135c85
Create Date: 2026-01-15 01:28:19.666554

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49189b8c0233"
down_revision: str | Sequence[str] | None = "e22ba8135c85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_completed_challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("completed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["challenge_id"], ["challenges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["completed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_completed_challenges_challenge_id"), "team_completed_challenges", ["challenge_id"], unique=False
    )
    op.create_index(op.f("ix_team_completed_challenges_id"), "team_completed_challenges", ["id"], unique=False)
    op.create_index(
        op.f("ix_team_completed_challenges_team_id"), "team_completed_challenges", ["team_id"], unique=False
    )
    op.create_index("uq_team_challenge_once", "team_completed_challenges", ["team_id", "challenge_id"], unique=True)
    op.add_column(
        "challenges",
        sa.Column(
            "protocol", sa.Enum("HTTP", "TCP", name="challenge_protocol_enum", native_enum=False), nullable=False
        ),
    )
    op.add_column("challenges", sa.Column("expose_tcp", sa.Boolean(), nullable=False))
    op.add_column("challenges", sa.Column("image_name", sa.String(length=128), nullable=False))
    op.add_column("challenges", sa.Column("internal_port", sa.Integer(), nullable=False))
    op.alter_column(
        "challenges", "flag", existing_type=sa.VARCHAR(length=512), type_=sa.String(length=128), existing_nullable=True
    )
    op.create_index("uq_user_challenge_once", "user_completed_challenges", ["user_id", "challenge_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_user_challenge_once", table_name="user_completed_challenges")
    op.alter_column(
        "challenges", "flag", existing_type=sa.String(length=128), type_=sa.VARCHAR(length=512), existing_nullable=True
    )
    op.drop_column("challenges", "internal_port")
    op.drop_column("challenges", "image_name")
    op.drop_column("challenges", "expose_tcp")
    op.drop_column("challenges", "protocol")
    op.drop_index("uq_team_challenge_once", table_name="team_completed_challenges")
    op.drop_index(op.f("ix_team_completed_challenges_team_id"), table_name="team_completed_challenges")
    op.drop_index(op.f("ix_team_completed_challenges_id"), table_name="team_completed_challenges")
    op.drop_index(op.f("ix_team_completed_challenges_challenge_id"), table_name="team_completed_challenges")
    op.drop_table("team_completed_challenges")
    # ### end Alembic commands ###
