"""fix migration

Revision ID: 6fc793797c30
Revises: f45996671e96
Create Date: 2025-11-03 17:38:31.747295

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "6fc793797c30"
down_revision: str | Sequence[str] | None = "f45996671e96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
