"""add user status

Revision ID: a8771c1010cb
Revises: 01987ddd48ba
Create Date: 2025-12-15 21:37:11.996383

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8771c1010cb"
down_revision: str | Sequence[str] | None = "01987ddd48ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the column as nullable first
    op.add_column(
        "users",
        sa.Column("status", sa.Enum("SUSPENDED", "ACTIVE", name="role_enum", native_enum=False), nullable=True),
    )
    # Set default to 'ACTIVE' for existing rows
    op.execute("UPDATE users SET status = 'ACTIVE' WHERE status IS NULL")
    # Alter to NOT NULL
    op.alter_column("users", "status", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "status")
    # ### end Alembic commands ###
