"""add challenge category+author defaults

Revision ID: b9d4869aea72
Revises: 49189b8c0233
Create Date: 2026-01-15 22:58:35.591094

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9d4869aea72"
down_revision: str | Sequence[str] | None = "49189b8c0233"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE challenges ADD COLUMN IF NOT EXISTS category VARCHAR(64);")
    op.execute("ALTER TABLE challenges ADD COLUMN IF NOT EXISTS author   VARCHAR(64);")

    # backfill
    op.execute("UPDATE challenges SET category='Uncategorized' WHERE category IS NULL;")
    op.execute("UPDATE challenges SET author='unknown' WHERE author IS NULL;")

    # enforce NOT NULL
    op.alter_column("challenges", "category", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.alter_column("challenges", "author", existing_type=sa.VARCHAR(length=64), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("challenges", "author", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.alter_column("challenges", "category", existing_type=sa.VARCHAR(length=64), nullable=True)
    # ### end Alembic commands ###
